# Generated by Django 3.1.4 on 2020-12-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0002_auto_20201219_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='public_viewing_allowed',
            new_name='public_profile',
        ),
    ]
