# Generated by Django 3.1.7 on 2021-05-31 10:08

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseapp', '0003_storystats'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniDome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
                ('battle_date', models.DateTimeField(auto_now_add=True)),
                ('minidome_type', models.PositiveSmallIntegerField(choices=[(1, 'LOGGED-IN - users of taste and distinction'), (2, 'PUBLIC - the great unwashed')], default=2, verbose_name='MiniDome Type')),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='baseapp.story')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='baseapp.story')),
            ],
            options={
                'verbose_name_plural': 'MiniDomes',
            },
        ),
    ]
