# Generated by Django 3.2.3 on 2021-06-12 22:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('universal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minidome',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
