# Generated by Django 3.2.3 on 2021-06-24 01:39

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('universal', '0002_alter_minidome_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CAIJ', 'Internal Judge Contest Annouce'), ('CAEJ', 'External Judge Contest Announce'), ('CC', 'Contest Close'), ('CR', 'Contest Results'), ('BCHA', 'Brawl Acceptance'), ('BACC', 'Brawl Acceptance'), ('BA', 'Brawl Challenge'), ('BC', 'Brawl Close'), ('BR', 'Brawl Result'), ('SA', 'Story Announce'), ('SYS', 'System')], default='SYS', max_length=4)),
                ('privacy', models.PositiveSmallIntegerField(choices=[(1, 'LOGGED-IN - users of taste and distinction'), (2, 'PUBLIC - the great unwashed')], default=1, max_length=4)),
                ('content', tinymce.models.HTMLField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='minidome',
            old_name='minidome_type',
            new_name='category',
        ),
    ]
