"""
Django settings for thunderdome project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
from django.contrib.messages import constants as messages
from dotenv import load_dotenv
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = str(os.getenv('SECRET_KEY'))


#ALLOWED_HOSTS = ['fumblemouse.pythonanywhere.com']



# Application definition
# Include profiles before contrib.auth to get in first
INSTALLED_APPS = [
    'profiles',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'baseapp',
    'promptarena',
    'tinymce',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
    'django_feature_policy.PermissionsPolicyMiddleware',
    'td2.td2_middleware.TimezoneMiddleware',
]

ROOT_URLCONF = 'td2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'td2.wsgi.application'



# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators
"""
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
"""

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Pacific/Auckland'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'


#LOGIN
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/set-timezone'


#Settings for email host
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'samsparx@gmail.com'
EMAIL_HOST_PASSWORD = str(os.getenv('SECRET_EMAIL_KEY'))
EMAIL_PORT = 587

#Messages for bootstrap

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info debug',
    messages.INFO: 'alert-info info',
    messages.SUCCESS: 'alert-success success',
    messages.WARNING: 'alert-warning warning',
    messages.ERROR: 'alert-danger error',
}


TINYMCE_SPELLCHECKER = True
TINYMCE_COMPRESSOR = False
TINYMCE_DEFAULT_CONFIG = {
    "theme": "silver",
    "height": 500,
    "menubar": False,
    "block_formats": "Paragraph=p; Heading=h3; Preformatted=pre",
    "plugins": "advlist,autolink,lists,charmap,print,preview,anchor,"
        "searchreplace,visualblocks,code,fullscreen,insertdatetime,media,table,paste,"
        "code,help,wordcount,hr",
    "toolbar": "fullscreen | formatselect | "
        "bold italic underline | undo redo | alignleft aligncenter "
        "alignright alignjustify | bullist numlist outdent indent | "
        "removeformat | preview save print | help",
    "resize":"both",
}

#Content Security Policy
CSP_DEFAULT_SRC = "'none'"
CSP_STYLE_SRC = (
    "'self'",
    'https://cdn.jsdelivr.net',
    'https://fonts.googleapis.com/',
    )
CSP_IMG_SRC =("'self'", 'data:')
#TODO remove unsafe inline
CSP_SCRIPT_SRC = ("'self'", 'https://cdn.jsdelivr.net',"'unsafe-inline'")
CSP_FONT_SRC = "https://fonts.gstatic.com"

#Feature Policy
PERMISSIONS_POLICY = {
    'accelerometer' : [],
#    'ambient-light-sensor' : [],
    'autoplay' : [],
 #  'battery' : [],
    'camera' : [],
    'cross-origin-isolated' : [],
#    'display-capture' : [],
    'document-domain' : [],
    'encrypted-media' : [],
#    'execution-while-not-rendered' : [],
#    'execution-while-out-of-viewport' : [],
    'fullscreen' : [],
    'geolocation' : [],
    'gyroscope' : [],
    'magnetometer' : [],
    'microphone' : [],
    'midi' : [],
#    'navigation-override' : [],
    'payment' : [],
    'picture-in-picture' : [],
    'publickey-credentials-get' : [],
    'screen-wake-lock' : [],
    'sync-xhr' : [],
    'usb' : [],
#    'web-share' : [],
#    'xr-spatial-tracking2' : [],
    }
