# Generated by Django 3.1.4 on 2021-01-28 02:14

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('bio', tinymce.models.HTMLField(blank=True)),
                ('public_profile', models.BooleanField(default=False, help_text='Leave this unchecked to keep your work private from anyone except necessary contestants.<em>NB:</em> If checked, you will still  need to set public visibility on each story', verbose_name='Public?')),
                ('timezone', models.CharField(default='Pacific/Auckland', max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(max_length=200)),
            ],
        ),
    ]
