# Generated by Django 3.2.3 on 2021-06-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='brawl_losses',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='brawl_wins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
