# Generated by Django 3.1.5 on 2021-03-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dms',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hms',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='losses',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='highest_access',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Only your darkest heart'), (1, 'Logged-in users of taste and distinction'), (2, 'The great unwashed')], default=2, help_text='Setting a value here will restrict all your stories to that                     level of privacy or more private. Eg, Selecting "Logged in" will make all of your Public                     stories only available to logged in users and prevent individual stories being set any higher.                     If this field is later set to a higher setting, individual stories                     will need their own privacy settings increased. Stories are Private by default', verbose_name='Sharing'),
        ),
    ]
