# Generated by Django 3.1.7 on 2021-04-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210330_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='public_profile',
        ),
        migrations.AddField(
            model_name='customuser',
            name='private_profile',
            field=models.BooleanField(default=False, help_text='Check this to keep your work private from anyone except your fellow contestants.         <em>NB:</em> If checked, you will still  need to set public visibility on each story', verbose_name='Private profile'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='highest_access',
            field=models.PositiveSmallIntegerField(choices=[(0, 'PRIVATE: Only your darkest heart'), (1, 'LOGGED-IN: Fellow users of taste and distinction'), (2, 'PUBLIC: The great unwashed')], default=2, help_text='Setting a value here will restrict all your stories to that                     level of privacy or more private. Eg, Selecting LOGGED-IN will make all of your PUBLIC                     stories only available to logged in users and prevent individual stories being set any higher.                     If this field is later set to a higher setting, individual stories                     will need their own privacy settings increased. Stories are Private by default', verbose_name='Restrict Story Sharing to:'),
        ),
    ]
