# Generated by Django 3.2.3 on 2021-06-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210622_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='brawler',
            field=models.BooleanField(default=True, help_text="Uncheck this if you don't want to be challenged to brawls", verbose_name='Brawler'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='private_profile',
            field=models.BooleanField(default=False, help_text='Check this if your anxiety gets too much for you.', verbose_name='Private profile'),
        ),
    ]
