# Generated by Django 3.1.4 on 2021-01-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_profile',
            field=models.BooleanField(default=False, help_text='While this box is unchecked, no-one can see your work except for fellow contest entrants.'),
        ),
    ]
