# Generated by Django 3.1.4 on 2021-01-13 03:06

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210112_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='public_profile',
            field=models.BooleanField(default=False, help_text='Leave this unchecked to keep your work private from anyone except necessary contestants.<em>NB:</em> If checked, you will still  need to set public visibility on each story'),
        ),
    ]
