# Generated by Django 3.1.7 on 2021-04-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210408_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='private_profile',
            field=models.BooleanField(default=False, help_text='Check this to keep your work private from anyone except your fellow contestants.', verbose_name='Private profile'),
        ),
    ]
