# Generated by Django 3.1.4 on 2021-01-14 00:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210113_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
