# Generated by Django 3.1.4 on 2021-01-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210114_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_profile',
            field=models.BooleanField(default=False, help_text='Leave this unchecked to keep your work private from anyone except necessary contestants.<em>NB:</em> If checked, you will still  need to set public visibility on each story', verbose_name='Public?'),
        ),
    ]
