# Generated by Django 3.1.4 on 2021-01-17 06:21

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210117_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='slug', max_length=200),
            preserve_default=False,
        ),
    ]
