# Generated by Django 3.2 on 2021-04-12 02:29

import autoslug.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', tinymce.models.HTMLField()),
                ('access', models.PositiveSmallIntegerField(choices=[(0, 'PRIVATE - Only your darkest heart'), (1, 'LOGGED-IN - users of taste and distinction'), (2, 'PUBLIC - Admit the great unwashed')], default=0, help_text='Caution: Making your story non-private will exclude it from entering contests', verbose_name='Who can see your story?')),
                ('slug', autoslug.fields.AutoSlugField(max_length=40, unique=True)),
                ('wordcount', models.PositiveSmallIntegerField()),
                ('has_been_public', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'stories',
            },
        ),
    ]
