# Generated by Django 3.1.4 on 2020-12-17 22:43

import autoslug.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'stories'},
        ),
        migrations.AddField(
            model_name='story',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='public_view_allowed',
            field=models.BooleanField(verbose_name='Display to non-logged in users?'),
        ),
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='no-story-slug', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
