# Generated by Django 3.1.7 on 2021-05-31 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryStats',
            fields=[
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats', serialize=False, to='baseapp.story')),
                ('minidome_public_wins', models.PositiveSmallIntegerField(default=0)),
                ('minidome_public_losses', models.PositiveSmallIntegerField(default=0)),
                ('minidome_logged_in_wins', models.PositiveSmallIntegerField(default=0)),
                ('minidome_logged_in_losses', models.PositiveSmallIntegerField(default=0)),
                ('minidome_total_wins', models.PositiveSmallIntegerField(default=0)),
                ('minidome_total_losses', models.PositiveSmallIntegerField(default=0)),
                ('minidome_total_public_tests', models.PositiveSmallIntegerField(default=0)),
                ('minidome_total_logged_in_tests', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
