# Generated by Django 3.1.4 on 2021-01-17 08:12

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_auto_20210117_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=autoslug.fields.AutoSlugField(max_length=40, unique=True),
        ),
        migrations.AddConstraint(
            model_name='story',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='unique_titles_for_authors'),
        ),
    ]
