# Generated by Django 3.1.4 on 2021-01-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_auto_20210117_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='has_been_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='public',
            field=models.BooleanField(help_text='Caution: Displaying a story publcially will exclude it from future contests', verbose_name='Show publically?'),
        ),
    ]
