# Generated by Django 3.2.3 on 2021-05-31 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_storystats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storystats',
            options={'verbose_name_plural': 'Story Stats'},
        ),
    ]
