# Generated by Django 3.2.3 on 2021-06-12 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_alter_storystats_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storystats',
            name='minidome_total_logged_in_tests',
        ),
        migrations.RemoveField(
            model_name='storystats',
            name='minidome_total_losses',
        ),
        migrations.RemoveField(
            model_name='storystats',
            name='minidome_total_public_tests',
        ),
        migrations.RemoveField(
            model_name='storystats',
            name='minidome_total_wins',
        ),
    ]
