# Generated by Django 3.1.4 on 2020-12-24 00:05

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('expiry_date', models.DateTimeField(verbose_name='Submit by Date')),
                ('wordcount', models.PositiveIntegerField(default=1000)),
                ('slug', autoslug.fields.AutoSlugField(default='no-contest-slug', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('content', tinymce.models.HTMLField()),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('slug', autoslug.fields.AutoSlugField(max_length=200, unique=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_scores', models.CharField(blank=True, max_length=200)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promptarena.contest')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.story')),
            ],
        ),
        migrations.CreateModel(
            name='Crits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
                ('score', models.IntegerField(choices=[(0, 'Select Score'), (3, 'Low'), (5, 'Low Middle'), (7, 'Middle'), (11, 'High Middle'), (13, 'High')], default=0)),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='promptarena.contest')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.story')),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='prompt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='promptarena.prompt'),
        ),
    ]
