# Generated by Django 3.2 on 2021-04-15 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promptarena', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='judge',
            new_name='judges',
        ),
        migrations.AlterField(
            model_name='contestjudges',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestjudges', to='promptarena.contest'),
        ),
        migrations.AlterField(
            model_name='contestjudges',
            name='judge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contestjudges', to=settings.AUTH_USER_MODEL),
        ),
    ]
