# Generated by Django 3.1.4 on 2020-12-18 07:04

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promptarena', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='slug',
            field=autoslug.fields.AutoSlugField(max_length=200, unique=True),
        ),
    ]
