# Generated by Django 3.1.5 on 2021-03-31 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_auto_20210401_1203'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promptarena', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='prompt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contests', to='promptarena.prompt'),
        ),
        migrations.AlterField(
            model_name='crit',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crits', to='promptarena.entry'),
        ),
        migrations.AlterField(
            model_name='crit',
            name='final',
            field=models.BooleanField(default=False, help_text='Check this box if you are finished with your critique. Be warned! - once submitted with this box checked no further edits can be made.'),
        ),
        migrations.AlterField(
            model_name='crit',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crit',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crits', to='baseapp.story'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='promptarena.contest'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='baseapp.story'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to=settings.AUTH_USER_MODEL),
        ),
    ]
