# Generated by Django 3.1.4 on 2020-12-27 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promptarena', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
    ]
