# Generated by Django 3.1.4 on 2020-12-31 04:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseapp', '0001_initial'),
        ('promptarena', '0002_auto_20201227_1318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crits',
            new_name='Crit',
        ),
    ]
