# Generated by Django 3.1.7 on 2021-04-05 09:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promptarena', '0002_auto_20210401_1203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrawlContest',
        ),
        migrations.CreateModel(
            name='ExternalJudgeContest',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('promptarena.contest',),
        ),
        migrations.AddField(
            model_name='contest',
            name='judges',
            field=models.ManyToManyField(related_name='contests_judged', to=settings.AUTH_USER_MODEL),
        ),
    ]
