# Generated by Django 3.2.3 on 2021-06-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptarena', '0002_auto_20210416_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='mode',
            field=models.CharField(choices=[('INTERNAL JUDGE CONTEST', 'Internal Judge Contest'), ('EXTERNAL JUDGE CONTEST', 'External Judge Contest'), ('Brawl', 'Brawl')], default='INTERNAL JUDGE CONTEST', max_length=22),
        ),
    ]
