# Generated by Django 3.2.3 on 2021-06-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptarena', '0003_alter_contest_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='mode',
            field=models.CharField(choices=[('IC', 'Internal Judge Contest'), ('EC', 'External Judge Contest'), ('BC', 'Brawl')], default='IC', max_length=2),
        ),
        migrations.AlterField(
            model_name='contest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unopened'), (1, 'Open'), (2, 'Judgement'), (3, 'Closed')], default=0),
        ),
    ]
