# Generated by Django 3.1.4 on 2021-01-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptarena', '0003_auto_20201231_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='crit',
            name='final',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
