# Generated by Django 3.1.7 on 2021-04-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promptarena', '0003_auto_20210405_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='judges',
        ),
    ]
