# Generated by Django 3.1.4 on 2021-01-04 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promptarena', '0004_crit_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crit',
            name='content',
            field=tinymce.models.HTMLField(help_text='Please enter your comments here'),
        ),
        migrations.AlterField(
            model_name='crit',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
