# Generated by Django 3.1.7 on 2021-04-06 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promptarena', '0004_remove_contest_judges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='prompt',
        ),
        migrations.AddField(
            model_name='contest',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contest',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Prompt',
        ),
    ]
