# Generated by Django 3.2.3 on 2021-07-08 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_auto_20210613_1040'),
        ('promptarena', '0005_auto_20210709_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='baseapp.story'),
        ),
    ]
