# Generated by Django 3.1.7 on 2021-04-09 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseapp', '0003_auto_20210401_1203'),
        ('promptarena', '0005_auto_20210407_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brawl',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('promptarena.contest',),
        ),
        migrations.RemoveField(
            model_name='crit',
            name='story',
        ),
        migrations.AlterField(
            model_name='contest',
            name='mode',
            field=models.CharField(choices=[('INTERNAL JUDGE CONTEST', 'Internal Judge Contest'), ('EXTERNAL JUDGE CONTEST', 'External Judge Contest')], default='INTERNAL JUDGE CONTEST', max_length=22),
        ),
        migrations.AlterField(
            model_name='entry',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='baseapp.story'),
        ),
        migrations.CreateModel(
            name='Contest_Judges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judges', to='promptarena.contest')),
                ('judge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='judge',
            field=models.ManyToManyField(blank=True, through='promptarena.Contest_Judges', to=settings.AUTH_USER_MODEL),
        ),
    ]
