# Generated by Django 3.1.4 on 2021-01-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptarena', '0005_auto_20210105_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('UNOPENED', 'Unopened'), ('OPEN', 'Open'), ('JUDGEMENT', 'Judgement'), ('CLOSED', 'Closed')], default='Unopened', max_length=9),
        ),
    ]
