# Generated by Django 3.1.4 on 2021-01-08 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promptarena', '0008_result_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crit',
            name='contest',
        ),
        migrations.AddField(
            model_name='crit',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='promptarena.entry'),
        ),
        migrations.AddField(
            model_name='crit',
            name='wordcount',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
