# Generated by Django 3.1.4 on 2021-01-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptarena', '0009_auto_20210108_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crit',
            name='wordcount',
            field=models.PositiveIntegerField(default=1000, null=True),
        ),
    ]
