# Generated by Django 3.1.4 on 2021-01-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptarena', '0010_auto_20210108_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='contest_scores',
        ),
        migrations.AddField(
            model_name='contest',
            name='entrant_num',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
