# Generated by Django 3.1.4 on 2021-01-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptarena', '0011_auto_20210110_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crit',
            name='final',
            field=models.BooleanField(blank=True, default=False, help_text='Check this box if you are finished with your critique. Be warned! - once submitted with this box checked no further edits can be made.'),
        ),
    ]
