# Generated by Django 3.1.4 on 2021-01-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptarena', '0012_auto_20210112_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crit',
            name='wordcount',
            field=models.PositiveIntegerField(default=100, null=True),
        ),
    ]
