# Generated by Django 3.1.4 on 2021-01-24 04:46

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptarena', '0014_auto_20210117_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrawlContest',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('promptarena.contest',),
        ),
        migrations.CreateModel(
            name='InternalJudgeContest',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('promptarena.contest',),
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='wordcount',
            new_name='max_wordcount',
        ),
        migrations.AddField(
            model_name='contest',
            name='mode',
            field=models.CharField(choices=[('INTERNAL JUDGE CONTEST', 'Internal Judge Contest'), ('BRAWL', 'Brawl')], default='INTERNAL JUDGE CONTEST', max_length=22),
        ),
        migrations.AlterField(
            model_name='contest',
            name='slug',
            field=autoslug.fields.AutoSlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('UNOPENED', 'Unopened'), ('OPEN', 'Open'), ('JUDGEMENT', 'Judgement'), ('CLOSED', 'Closed')], default='UNOPENED', max_length=9),
        ),
    ]
